config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :sooqadministrationmembers do
    resources :hrists
    resources :eikonas
    resources :proions do
      resources :eikonas, shallow: true
    end
    resources :categories
    resources :orders
    resources :riders
    resources :deliveries
    resources :tags
    resources :tagged_products
    resources :users
    resources :locations
    resources :user_locations

    root to: 'hrists#index'
  end

  devise_for :hrists

  namespace :api do
    namespace :v1 do
      scope :market do
        resources :proions, only: [:create, :destroy]
      end
    end
  end

  scope "(:locale)", locale: /mk|sq/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    devise_for :riders, controllers: {
      registrations: 'riders/registrations',
      sessions: 'riders/sessions'
    }

    devise_scope :user do
      post 'users/continue_as_guest', to: 'users/sessions#continue_as_guest', as: 'continue_as_guest'
    end

    get 'riders/:id' => 'riders#show', as: 'rider'


    resources :proions, path: 'products'
    resources :categories, key: :reference
    resources :orders
    resources :deliveries
    resources :locations

    get 'carts/cart_checkout' => 'carts#cart_checkout', as: 'cart_checkout'
    get 'carts/:id' => 'carts#show', as: 'cart'
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#show', as: 'line_item'
    delete 'line_items/:id' => 'line_items#destroy'

    post '/navigate-category', to: 'categories#navigate_category'
    get '/shop', to: 'pages#shop', as: :shop
    root 'pages#index', as: :pages_index
  end
end

app/views/shared/_footer.html.erb
<div  style="width:  100% !important;background-color:#fce7f1; padding:0.5rem;opacity:1"></div>
<footer >
  <div class="columns mt-5 is-flex is-justify-content-center has-text-left is-align-content-center is-flex-direction-row-desktop is-flex-direction-column-mobile   has-text-centered" id="left-float-whenis-mobile">
    <div class="column is-2  mr-5">
      <%= image_tag("logo_hero.png", :size => "135x135") %>
    </div>
    <div class="column ml-2-mobile mt-2-mobile ml-5-desktop is-1 has-text-left"style="color:#022855;width:15rem" >
      <div class="title is-4" style="color:#022855"><%= t('.about') %></div>
      <div style="color:#022855"><%= t('.careers') %></div>
      <div class="mt-2"style="color:#022855"><%= t('.faq') %></div>
    </div>
    <div class="column ml-2-mobile mt-2-mobile mt-2-mobile is-1 has-text-left"style="color:#022855;width:15rem">
      <div class="title is-4"style="color:#022855;"><%= t('.social') %></div>
      <div class="is-flex " id="social-media">
        <i class="fa-brands fa-square-instagram mr-3 fa-2x"></i>
        <i class="fab fa-facebook-f fa-2x mr-3"></i>
        <i class=" mr-3 fa-brands fa-linkedin fa-2x"></i>
      </div>
    </div>
    <div class="column ml-2-mobile is-1  mt-2-mobile  has-text-left "style="color:#022855;width:15rem; display: none;">
      <div class="title is-4 is-flex is-flex-direction-column has-"style="color:#022855"><%= t('.apps') %>
        <div class="mt-2 " id="download-images"><a>      <%= image_tag("app-store.png", :size => "200x200") %></a></div>
        <div class="mt-2 " id="download-images1"><a>      <%= image_tag("googleplayy.png", :size => "170x170") %></a></div>
      </div>
    </div>
  </div>
</div>
<div class="section is-hidden">
  <div class="container">
    <div>
      <hr style="width:100%;border-top-width:1px;--tw-border-opacity:1;border-color:rgba(222, 222, 222, var(--tw-border-opacity));">
    </div>
    <div class="is-flex is-justify-content-space-between"  id="left-float-whenis-mobile">
      <div class=" is-flex" style="width:60rem;gap:1rem;  "id="left-float-whenis-mobile">
        <div class=" mr-auto " style="color:#022855">© 2022 Sooq SE </div>
        <div class=" mr-auto " style="color:#022855"><%= t('.terms') %> </div>
        <div class=" mr-auto " style="color:#022855"><%= t('.privacy') %>  </div>
        <div class=" mr-auto is-pulled-left" style="width:1rem;flex-grow:1 !important;color:#022855"><%= t('.cookie') %>  </div>
      </div>
      <div class=" is-flex" id="left-float-whenis-mobile"style=";gap:1rem;color:#022855 ">
        <div class="mt-5-mobile">
          <i class="fa-solid fa-location-dot"></i>
          Skopje - MK
        </div>
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
<section class="hero navbar is-fixed-top <%= content_for?(:pages_index) ? yield(:pages_index) : "" %>">
  <div class="hero-body hero-body-header is-flex is-justify-content-space-between is-align-items-center">
    <a href="/">
      <p class="title title-pages is-flex">
        <%= image_tag("logo_hero.png",size:"150x150")%>
      </p>
    </a>
    <% if content_for?(:shop) %>
      <div class="field" style="margin: 0px;">
        <div class="control">
          <p class="control has-icons-left has-icons-right is-hidden-mobile ">
            <input class="input" type="email" placeholder="<%= t('.search') %>">
            <span class="icon is-small is-left">
              <i class="fas fa-search"></i>
            </span>
          </p>
        </div>
      </div>
    <% end %>
    <div class="is-flex" id="mobile-width">
      <div id="cart-details" style="<% if @current_cart.present? && @current_cart.line_items.present? %><% else %>display: none;<% end %>">
        <% unless action_name == "index" %>
          <%= render 'carts/cart_nav', cart: @current_cart %>
        <% end %>
      </div>
      <% if !content_for?(:pages_index) %>
        <div id="account-section" class="is-flex is-align-items-center">
          <div class="" id="dropdownTrigger">
            <div class="user-account-icon ml-5">
              <i style="font-size: 20px;" class="fa-regular fa-user"></i>
            </div>
          </div>
          <div class="dropdown-menu" id="dropdown-menu4" role="menu">
            <div class="dropdown-content">
              <div class="dropdown-item">
                <div class="is-flex">
                  <p class="mr-6"><%= t('.choose_language') %>:</p>
                  <%= render 'shared/i18n' %>
                </div>
                <% if current_user.present? %>
                  <hr style="margin: 1em 0;">
                  <div class="is-flex">
                    <a class="is-link" href="<%= orders_path(locale: I18n.locale) %>" style="color: #022855; font-weight: 600; padding-left: 0px;"><%= t('.orders') %></a>
                  </div>
                <% end %>
                <hr style="margin: 1em 0;">
                <div class="is-flex">
                  <% if current_user.present? %>
                    <%= button_to t('.sign_out'), destroy_user_session_path, {class: 'authorization-btn is-link', style: 'padding-left: 0px;', method: :delete}  %>
                  <% else %>
                    <%= button_to t('.sign_in'), new_user_session_path, {class: 'authorization-btn is-link', style: 'padding-left: 0px;', method: :get}  %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if content_for?(:pages_index) %>
      <div>
        <%= render 'shared/i18n' %>
      </div>
    <%end%>
    <% if !content_for?(:pages_index) %>
      <div style="display:none;">
        <% if current_hrist.present? %>
          <%= button_to "Sign out", destroy_hrist_session_path, {class: 'authorization-btn is-link', method: :delete}  %>
        <% else %>
          <%= button_to "Sign in", new_hrist_session_path, {class: 'authorization-btn is-link', method: :get}  %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id="cart-details-modal">
    <%= render 'carts/cart', cart: @current_cart %>
  </div>
</section>
<div class="mb-2">
  <hr style="width:100%;border-top-width:1px;--tw-border-opacity:1;border-color:rgba(222, 222, 222, var(--tw-border-opacity));">
</div>

app/views/shared/_i18n.html.erb
<div class="tags are-normal">
    <%= link_to url_for(locale: :mk) do %>
        <img style="width: 25px; margin-right: 10px;" alt="MK" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/MK.svg"/>
    <% end %>
    <%= link_to url_for(locale: :sq) do %>
        <img style="width: 25px;" alt="SQ" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/AL.svg"/>
    <% end %>
</div>

app/views/shared/_promotions.html.erb
<div>
  <section class="section" style="background-color:#fcd4dc">
    <div class="container">
      <div class="columns is-vcentered is-centered has-text-centered-mobile	">
        <div class="column is-3-tablet is-3-desktop  ">
          <div class="myHero ">
            <div style="margin-bottom:15px">
              <%= image_tag("logo_hero.png", :size => "200x135") %>
            </div>
            <div class="conent-is-medium">
              <h1 class="title is-3 mb-6" style="color:#022855">Groceries delivered in minutes</h1>
              <p class="subtitle is-5" style="color:#022855">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta a et ipsa voluptates in velit rem minus nihil, blanditiis nisi, quidem tempore quos qui quas. Blanditiis hic dolorem fugiat? Blanditiis!</p>
            </div>
            <div class=" mt-4 has-text-centered-mobile">
              <button class="button is-danger ">Danger</button>
            </div>
          </div>
        </div>
        <div class="column  is-7 is-7-tablet is-7-desktop is-5 ml-5" >
          <figure class="image is4by3">
            <%= image_tag("home1.png") %>
          </figure>
        </div>
      </div>
    </div>
  </section>
</div>
<section class="section">
  <div class="container">
    <div class="title is-2  pb-3 has-text-centered pull" style="color:#022855">
      Need Something Sooq it!
    </div>
    <p class="subtitle is-5 has-text-centered pb-6"> Explore our assortment of fresh fruit, vegetables, bread and more...</p>
    <div class="columns  is-mobile is-tablet  is-flex is-justify-content-center	is-align-content-center	is-flex-wrap-wrap" style="gap:4rem; flex-wrap:wrap">
      <div class="card-content" style=" width:11rem; height:10rem; background-color:#e3f7f7" >
        <%= image_tag("chips.png", :size => "90x85",:style => 'margin-left: 1.4rem;') %>
        <div class="subtitle is-6 mt-4 has-text-centered">
          <div class="subtitle is-6 "> Salty snacks </div>
        </div>
      </div>
      <div class="card-content  	"style=" width:11rem; height:10rem; background-color:#e3f7f7">
        <%= image_tag("pngegg.png", :size => "200x55",:style => 'margin-left: 0.5rem;') %>
        <div class=" is-align-conent-center mt-2 ">
          <div class="subtitle is-6 "> fruits & vegetables</div>
        </div>
      </div>
      <div class="card-content is-align-content-center "style="width:11rem;height:10rem; background-color:#e3f7f7">
        <%= image_tag("eggmilk.png", :size => "100x85",:style => 'margin-bottom:0.4rem; margin-left: 0.5rem;') %>
        <div class="subtitle is-6 mt-4 has-text-centered">
          <p> Eggs & Milk </p>
        </div>
      </div>
      <div class="card-content is-align-content-center "style="width:11rem;height:10rem;background-color:#e3f7f7">
        <%= image_tag("cola.png", :size => "200x100",:style => ' margin-bottom:0.7rem;margin-left:0.1; margin-top:-1rem;') %>
        <div class="is-align-conent-center mt-3 ">
          <div style="width:150px"class="subtitle is-6 "> Fruits & Vegetables</div>
        </div>
      </div>
    </div>
    <section class="sectiion">
      <div style="text-align:center;margin-top:100px">
        <div class="button is-danger has-text-centered py-5 px-6 has-text-weight-bold	" > Explore Categories</div>
      </div>
    </section>
  </div>
</section>
<div class="section" >
  <div class="title is-1 has-text-centered-mobile has-text-centered" style="color:#022855">
    Why Sooq?
  </div>
  <div class="container ">
    <div class="columns mt-6 has-text-centered  is-flex is-justify-content-center is-flex-wrap-wrap	is-align-content-center	" >
      <div class="column is-3-desktop  is-5-tablet is-7-mobile 	is-flex-wrap-wrap"  style="width:17rem;">
        <%= image_tag("groceries.svg", :size => "110x100") %>
        <div class="title is-6 ">
          Supermarket Prices
        </div>
        <div class="subtitle is-6" >
          Over 2000 items, direct to your door, at normal supermarket prices!
        </div>
      </div>
      <div class="column is-3-desktop  is-5-tablet is-5-mobile " style="width:17rem;">
        <%= image_tag("fast.svg", :size => "110x100") %>
        <div class="title is-6 ">
          Supermarket Prices
        </div>
        <div class="subtitle is-6" >
          Over 2000 items, direct to your door, at normal supermarket prices!
        </div>
      </div>
      <div class="column is-3-desktop is-5-mobile  is-5-tablet" style="width:17rem;">
        <%= image_tag("diet.svg", :size => "110x100") %>
        <div class="title is-6 ">
          Supermarket Prices
        </div>
        <div class="subtitle is-6" >
          Over 2000 items, direct to your door, at normal supermarket prices!
        </div>
      </div>
    </div>
    <section class="section is-mobile-6 is-desktop-6 is-tablet-6">
      <div style="text-align:center;margin-top:2em">
        <div class="button is-danger has-text-centered py-5 px-6 has-text-weight-bold" > Start Shopping</div>
      </div>
    </section>
  </div>
</div>
</div>
<div class="section" >
  <div class="container ">
    <div class="columns  is-flex is-justify-content-center is-multiline  is-flex-wrap-wrap is-align-content-center	" >
      <div class="column is-4-desktop  is-6-tablet is-6-mobile is-flex-direction-column-mobile flex-direction-column-tablet"  style="width:30rem;">
        <div class="title is-3 has-text-left-desktop has-text-centered-tablet has-text-centered-mobile"style="color:#022855"  >
          Our delivery areas
        </div>
        <div class="subtitle is-4 has-text-left-desktop has-text-centered-mobile has-text-centered-tablet ">
          Find the cities where we deliver your grocery and ready to eat meals, in minutes and at supermarket prices.
        </div>
        <div class="pb-4 has-text-left-desktop has-text-centered-mobile has-text-centered-tablet ">
          <div class="button is-danger py-5 px-6 has-text-weight-bold	" > Start Shopping</div>
        </div>
        <div class="is-centered-tablet has-text-left-desktop has-text-centered-tablet has-text-centered-mobile ">
          <%# <div class="is-flex has-text-centered-mobile is-flex-wrap-wrap  is-align-content-center is-centered-mobile "> %>
          <div>
            <span class="is-pulled-left-desktop is-pulled-left-mobile is-pulled-left-tablet "> City not listed?</span>
            <span><a href="#"class="is-pulled-left-desktop  has-text-centered-mobile ml-2 "> Signup for our waitlist </a></span>
          </div>
        </div>
      </div>
      <div class="is-centered-tablet has-text-centered-tablet has-text-centered-mobile ">
        <div class="column is-4-desktop is-2-tablet is-2-mobile is-centered-tablet is-centered-mobile has-text-centered-mobile has-text-centered-tablet mr-5">
          <div class="title is-3 ml-6" style="width:20rem">
            <%= image_tag("Skopje_in_North_Macedonia.svg", size: "400x400",style:"  border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%;") %>
          </div>
        </div>
      </div>
      <div class="columns mt-5  has-text-centered  is-flex is-justify-content-left is-flex-wrap-wrap	is-align-content-center	" >
        <div class="column is-12-mobile">
          <div class="tag is-medium is-info is-light"style="border-radius:0.5rem; height:2.5rem;width:12.5rem;" >
            <p class="subtitle is-5" style="color:#022855;padding:0 1.1rem">Shkup</p>
          </div>
        </div>
        <div class="column is-12-mobile">
          <div class="tag is-medium is-info is-light"style="border-radius:0.5rem;height:2.5rem;width:12.5rem;" >
            <p class="subtitle is-5" style="color:#022855;padding:0 1.1rem">Vizbeg</p>
          </div>
        </div>
        <div class="column is-12-mobile">
          <div class="tag is-medium is-info is-light"style="border-radius:0.5rem;height:2.5rem;width:12.5rem;" >
            <p class="subtitle is-5" style="color:#022855;padding:0 1.1rem">Karposh</p>
          </div>
        </div>
        <div class="column is-12-mobile">
          <div class="tag is-medium is-info is-light"style="border-radius:0.5rem;height:2.5rem;width:12.5rem;" >
            <p class="subtitle is-5" style="color:#022855;padding:0 1.1rem">Centar</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>
<div>
  <div style="background: url('/assets/grocerydelivery.jpg'); width: 100%; height:400px ; background-attachment:fixed;
    background-size:cover;   
    background-size:cover;
    font-family: 'Lato', sans-serif;
    display:block;">
  </div>