config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :sooqadministrationmembers do
    resources :hrists
    resources :eikonas
    resources :proions do
      resources :eikonas, shallow: true
    end
    resources :categories
    resources :orders
    resources :riders
    resources :deliveries
    resources :tags
    resources :tagged_products
    resources :users
    resources :locations
    resources :user_locations

    root to: 'hrists#index'
  end

  devise_for :hrists

  namespace :api do
    namespace :v1 do
      scope :market do
        resources :proions, only: [:create, :destroy]
      end
    end
  end

  scope "(:locale)", locale: /mk|sq/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    devise_for :riders, controllers: {
      registrations: 'riders/registrations',
      sessions: 'riders/sessions'
    }

    devise_scope :user do
      post 'users/continue_as_guest', to: 'users/sessions#continue_as_guest', as: 'continue_as_guest'
    end

    get 'riders/:id' => 'riders#show', as: 'rider'


    resources :proions, path: 'products'
    resources :categories, key: :reference
    resources :orders
    resources :deliveries
    resources :locations

    get 'carts/cart_checkout' => 'carts#cart_checkout', as: 'cart_checkout'
    get 'carts/:id' => 'carts#show', as: 'cart'
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#show', as: 'line_item'
    delete 'line_items/:id' => 'line_items#destroy'

    post '/navigate-category', to: 'categories#navigate_category'
    get '/shop', to: 'pages#shop', as: :shop
    root 'pages#index', as: :pages_index
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :proions, through: :line_items

  # LOGIC
  def sub_total
    line_items.map(&:total_price).sum
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!, only: :cart_checkout
  before_action :get_current_user, only: :cart_checkout

  def show
    @cart = @current_cart

    render json: { html: render_to_string(partial: 'carts/cart', locals: { cart: @cart }) }
  end

  def cart_checkout
    @show_location = @current_user.present? && @current_user.locations.blank? ? true : nil
    @cart = @current_cart
    @order = Order.new
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def get_current_user
    @current_user = current_user if current_user.present?
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="modal-background" id="modal-background"></div>
<i class="fa-solid fa-caret-up" id="modal-arrow" style="display: none;"></i>
<div class="modal" id="cart-modal">
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title" style="color: black;"><%= t('.shopping_cart') %></p>
      <a href="#" data-controller="add-to-cart" data-action="click->add-to-cart#closeCart">
        <button class="delete" aria-label="close"></button>
      </a>
    </header>
    <section class="modal-card-body" id="cart-nav-modal-body">
      <div id="add-reduce-section">
        <%= render "carts/proion", line_items: cart.line_items, from_cart_checkout: false %>
      </div>
    </section>
    <p style="padding: 10px 20px; background-color: white; font-size: 13px; font-weight: 500; "><%= t('.checkout_limit') %>*</p>
    <footer class="modal-card-foot">
      <a id="proceed-to-checkout" href="<%= cart_checkout_path(locale: I18n.locale) %>" class="button is-danger <% if (cart.present? && cart.sub_total < 1000) || cart.blank? %>disabled-link<% end %>"><%= t('.checkout') %></a>
      <a href="#" data-controller="add-to-cart" data-action="click->add-to-cart#closeCart">
        <button class="button is-light"><%= t('.cancel') %></button>
      </a>
    </footer>
  </div>
</div>

app/views/carts/_cart_nav.html.erb
<a id="cart-nav" href="#" data-controller="add-to-cart" data-add-to-cart-load-path="<%= cart_path(@current_cart) %>" data-action="click->add-to-cart#openCart">
  <div class="columns cart-nav  is-flex is-justify-content-centered is-align-items-center" id="mobile-width-cart-nav">
    <div class="column price-div has-background-danger ">
      <i class="has-text-white is-pulled-left fa fa-shopping-bag is-3" aria-hidden="true"  style="position: absolute; top:18px; width: 20px; height: 20px;"></i>
      <div class="is-flex is-flex-direction-column ml-5 card-nav-mt-mobile">
        <span class="has-text-right has-text-white ml-5 is-pulled-right font-size-subtotal-mobile" style="position: relative; top: 5px;"><% if cart.sub_total != 0 %><span id="total-amount"><%= cart.sub_total %></span> <span class="currency"><%= t('.den') %></span><% end %></span>
        <!-- <span class="is-pulled-right has-text-right subtitle has-text-white is-7 is-hidden" id="delivery-price"> <%= t('.70') %><span class="currency"><%= t('.den') %></span> <%= t('.delivery') %></span> -->
      </div>
    </div>
  </div>
</a>

app/views/carts/_proion.html.erb
<% line_items.each do |line_item| %>
    <%
        proion = line_item.proion
        eikona = proion.eikonas.present? && proion.eikonas.find_by(thumbnail: "true").present? ? proion.eikonas.find_by(thumbnail: "true") : ""
        from_cart_checkout = from_cart_checkout.present? ? from_cart_checkout : nil
    %>
    <div class="is-flex is-justify-content-space-between is-align-items-end mt-3 mb-3">
        <div class="is-flex is-align-items-end <% if from_cart_checkout.present? && from_cart_checkout == true %>checkout-proion-image-section<% end %>" style="max-width: 200px;">
            <div class="product-image is-flex is-align-center is-justify-content-center"style="position:relative">
                <span class="is-flex is-align-items-center is-justify-content-center">
                    <% if eikona.present? && eikona.respond_to?(:image) && eikona.image.attached? %>
                        <%= image_tag(eikona.image, :size => "80x80",style:"margin:0 auto;") %>
                    <% else %>
                        <%= image_tag("domestos.png", :size => "80x80",style:"margin:0 auto;") %>
                    <% end %>
                </span>
            </div>
        </div>
        <div class="is-flex is-flex-direction-column" style="width: 100%; height: 125px; justify-content: space-around;">
            <div class="is-flex">
                <div class="ml-2">
                    <p style="font-size: 12px;"><%= proion.price %> <span class="currency"><%= t('carts.cart_nav.den') %></span></p>
                    <p style="font-weight: 500; font-size: 12px;"><%= proion.title %></p>
                </div>
            </div>
            <div class="is-flex is-align-items-end is-justify-content-end">
                <div class="is-flex is-align-items-center add-or-reduce" style="height: 40px;">
                    <div class="is-flex p-5px is-justify-content-center">
                        <a class="is-flex is-justify-content-center" href="#" data-controller="add-to-cart" data-add-to-cart-load-path="<%= line_item_reduce_path(:id => line_item) %>" data-action="click->add-to-cart#addReduceCart">
                            <%= image_tag("minus-svgrepo-com.svg", :size => "25x25") %>
                        </a>
                    </div>
                    <div class="p-5px quantity-background">
                        <p class="has-text-centered"><%= line_item.quantity %><p>
                    </div>
                    <div class="is-flex p-5px is-justify-content-center">
                        <a class="is-flex is-justify-content-center" href="#" data-controller="add-to-cart" data-add-to-cart-load-path="<%= line_item_add_path(:id => line_item) %>" data-action="click->add-to-cart#addReduceCart">
                            <%= image_tag("plus-svgrepo-com.svg", :size => "25x25") %>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/carts/cart_checkout.html.erb
<div class="hero is-medium">
    <div class="hero-body">
        <div class="columns columns-margin-mobile is-mobile">
            <div class="column is-three-fifths-desktop is-full-touch m-0-mobile is-offset-one-fifth">
                <%= form_with model: @order, id: "order-form" do |form| %>
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                            <%= t('.cart_details') %>
                            </p>
                        </header>
                        <div class="card-content">
                            <div id="add-reduce-second-section">
                                <%= render "carts/proion", line_items: @cart.line_items, from_cart_checkout: true %>
                            </div>
                            <!-- Pass products -->
                            <hr />
                            <div class="mb-4 is-flex is-justify-content-space-between" style="font-size: 15px; font-weight: 500;">
                                <span class="is-flex is-align-items-center"><%= t('.address') %>:</span>
                                <span class="is-flex is-align-items-center">
                                    <div class="control">
                                        <div id="full-address" class="select" style="margin-right: 15px;">
                                            <% if @current_user.present? && @current_user.user_locations.present? %>
                                                <%= form.select :user_location_id, @current_user.user_locations.collect {|user_location| [ user_location.location.address, user_location.id ]}, selected: @current_user.user_locations.most_recently_created %>
                                            <% end %>
                                        </div>
                                    </div>
                                    <a href="#" id="openLocationLink" class="font-mobile" data-controller="location" data-action="click->location#openLocation"><%= t('.add_address') %></a>
                                </span>
                            </div>
                            <hr />
                            <div class="is-flex is-justify-content-space-between" style="font-size: 15px; font-weight: 500;">
                                <span><%= t('.total') %>:</span><span><span id="total-second-amount"><%= @cart.sub_total %></span> <span class="currency"><%= t('carts.cart_nav.den') %></span></span>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <button href="#" id="order-button" class="card-footer-item <% if @show_location.present? || (@cart.sub_total.present? && @cart.sub_total.to_i < 1000) %>disabled<% end %>"><%= t('.order') %></button>
                            <a href="<%= shop_path(locale: I18n.locale) %>" class="card-footer-item"><%= t('.go_back') %></a>
                        </footer>
                    </div>
                    <input style="display:none;" type="text" value="" name="order[line_item_ids][]" id="order_line_item_ids">
                    <% @current_cart.line_items.each do |line_item| %>
                        <input style="display:none;" checked type="checkbox" value="<%= line_item.id %>" name="order[line_item_ids][]" id="order_line_item_ids_<%= line_item.id %>">
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<%= render 'locations/location', current_user: @current_user, location: @location, show_location: @show_location %>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>