config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :sooqadministrationmembers do
    resources :hrists
    resources :eikonas
    resources :proions do
      resources :eikonas, shallow: true
    end
    resources :categories
    resources :orders
    resources :riders
    resources :deliveries
    resources :tags
    resources :tagged_products
    resources :users
    resources :locations
    resources :user_locations

    root to: 'hrists#index'
  end

  devise_for :hrists

  namespace :api do
    namespace :v1 do
      scope :market do
        resources :proions, only: [:create, :destroy]
      end
    end
  end

  scope "(:locale)", locale: /mk|sq/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    devise_for :riders, controllers: {
      registrations: 'riders/registrations',
      sessions: 'riders/sessions'
    }

    devise_scope :user do
      post 'users/continue_as_guest', to: 'users/sessions#continue_as_guest', as: 'continue_as_guest'
    end

    get 'riders/:id' => 'riders#show', as: 'rider'


    resources :proions, path: 'products'
    resources :categories, key: :reference
    resources :orders
    resources :deliveries
    resources :locations

    get 'carts/cart_checkout' => 'carts#cart_checkout', as: 'cart_checkout'
    get 'carts/:id' => 'carts#show', as: 'cart'
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#show', as: 'line_item'
    delete 'line_items/:id' => 'line_items#destroy'

    post '/navigate-category', to: 'categories#navigate_category'
    get '/shop', to: 'pages#shop', as: :shop
    root 'pages#index', as: :pages_index
  end
end

app/models/proion.rb
# frozen_string_literal: true

class Proion < ApplicationRecord
  before_save :adjust_price, if: :market_price_changed?

  attr_accessor :tag_names

  belongs_to :category, optional: true
  has_many :eikonas
  accepts_nested_attributes_for :eikonas, reject_if: :all_blank, allow_destroy: true
  has_many :tagged_products, dependent: :delete_all
  has_many :tags, through: :tagged_products

  def price_to_calculate
    price.present? ? price.to_i : 0
  end

  def main_image
    return false unless check_for_images

    eikonas.where(thumbnail: 'true').pluck(:path_ref).first
  end

  def check_for_images
    eikonas.present?
  end

  def save_and_link_tag(params)
    transaction do
      save!
      link_tags!(params[:tag_names])
    rescue ActiveRecord::ActiveRecordError
      return_value = false
      raise ActiveRecord::Rollback
    end
  end

  def update_and_link_tag(params)
    transaction do
      update!(params)
      link_tags!(params[:tag_names])
    rescue ActiveRecord::ActiveRecordError
      return_value = false
      raise ActiveRecord::Rollback
    end
  end

  def create_eikonas_for_proion(images)
    return nil if images.blank?

    images.each_with_index do |image, index|
      if image.present?
        thumbnail = index == 0 ? "true" : "false"
        eikona = Eikona.create!(proion_id: id, thumbnail: thumbnail)
        eikona.image.attach(image)
      end
    end
  end

  private

  def adjust_price
    self.price = "#{custom_round(market_price.to_f * 1.05)}"
  end

  def custom_round(number)
    if number - number.floor >= 0.5
      number.ceil
    else
      number.floor
    end
  end

  def link_tags!(tag_names)
    return TaggedProduct.where(proion_id: id).destroy_all if tag_names.blank?

    tags = Tag.where(name: tag_names.split(', '))
    tagged_products = TaggedProduct.where(tag_id: tags.map(&:id), proion_id: id)

    tag_names.split(', ').each_with_index do |name, _position|
      tag = Tag.find_by!(name: name)

      # if break doesnt work use if if
      if tag.present? && TaggedProduct.find_by(tag_id: tag.id, proion_id: id).blank?
        TaggedProduct.create(tag_id: tag.id, proion_id: id)
      end
    end
  end
end

app/controllers/admin/proions_controller.rb
# frozen_string_literal: true

module Admin
  class ProionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    def new
      @tags = Tag.all
      super
    end

    def edit
      @tags = Tag.all
      @tags_selected = Proion.find(params[:id]).tags.map(&:name)
      super
    end

    def create
      resource = resource_class.new(resource_params)
      authorize_resource(resource)

      proion = Proion.new(proion_params)

      if proion.save_and_link_tag(proion_params)
        redirect_to(
          after_resource_created_path(resource),
          notice: translate_with_resource('create.success')
        )
      else
        @tags = Tag.all

        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource)
        }, status: :unprocessable_entity
      end
    end

    def update
      proion = Proion.find(params[:id])

      if proion.update_and_link_tag(proion_params)
        redirect_to(
          after_resource_updated_path(requested_resource),
          notice: translate_with_resource('update.success')
        )
      else
        @tags = Tag.all
        @tags_selected = Proion.find(params[:id]).tags.map(&:name)

        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource)
        }, status: :unprocessable_entity
      end
      # send_foo_updated_email(requested_resource)
    end

    private

    def after_resource_created_path(requested_resource)
      [namespace, requested_resource]
    end

    def after_resource_updated_path(requested_resource)
      [namespace, requested_resource]
    end

    def proion_params
      params.require(:proion).permit(
        :title,
        :description,
        :price,
        :size,
        :category_id,
        :previous_price,
        :long_description,
        :energy,
        :fat,
        :carbs,
        :fibre,
        :protein,
        :salt,
        :sugar,
        :tag_names
      )
    end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/proions_controller.rb
module Api
  module V1
    class ProionsController < ApplicationController
      skip_before_action :verify_authenticity_token
      
      def create
        proions_params.each do |proion_params|
          proion = Proion.find_or_initialize_by(market_proion_id: proion_params[:market_proion_id])
          proion.update(proion_params)
        end

        head :ok
      end

      def destroy
        Proion.where.not(market_proion_id: [nil, ""]).destroy_all
      end

      private

      def proions_params
        params.require(:proions).map { |proion| proion.permit(:market_proion_id, :title, :market_price) }
      end
    end
  end
end

app/controllers/proions_controller.rb
# frozen_string_literal: true

class ProionsController < ApplicationController
  def index
    @proions = Proion.all
    # except hottest, etcc.
    # kur ta trusin ni kategori qato i qel kejt
  end

  def show
    @proion = Proion.find(params[:id])

    render json: { html: render_to_string(partial: 'proions/proion_details', locals: { proion: @proion }) }
  end
end

app/controllers/sooqadministrationmembers/proions_controller.rb
# frozen_string_literal: true

module Sooqadministrationmembers
  class ProionsController < Sooqadministrationmembers::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    def new
      @tags = Tag.all
      @proion = Proion.new # Create a new Proion object
      3.times { @proion.eikonas.build } # Build associated Eikona objects
    
      super
    end

    def edit
      @tags = Tag.all
      @tags_selected = Proion.find(params[:id]).tags.map(&:name)
      super
    end

    def create
      resource = resource_class.new(resource_params)
      authorize_resource(resource)

      proion = Proion.new(proion_params)

      if proion.save_and_link_tag(proion_params)
        proion.create_eikonas_for_proion(proion_image_params[:images]) if proion_image_params[:images].present?
        
        redirect_to(
          after_resource_created_path(resource),
          notice: translate_with_resource('create.success')
        )
      else
        @tags = Tag.all

        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource)
        }, status: :unprocessable_entity
      end
    end

    def update
      proion = Proion.find(params[:id])

      if proion.update_and_link_tag(proion_params)
        proion.create_eikonas_for_proion(proion_image_params[:images]) if proion_image_params[:images].present?
        
        redirect_to(
          after_resource_updated_path(requested_resource),
          notice: translate_with_resource('update.success')
        )
      else
        @tags = Tag.all
        @tags_selected = Proion.find(params[:id]).tags.map(&:name)

        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource)
        }, status: :unprocessable_entity
      end
      # send_foo_updated_email(requested_resource)
    end

    private

    def after_resource_created_path(requested_resource)
      [namespace, requested_resource]
    end

    def after_resource_updated_path(requested_resource)
      [namespace, requested_resource]
    end

    def proion_params
      params.require(:proion).permit(
        :title,
        :description,
        :price,
        :size,
        :category_id,
        :previous_price,
        :price_per_size,
        :market_price,
        :long_description,
        :energy,
        :fat,
        :carbs,
        :fibre,
        :protein,
        :salt,
        :sugar,
        :tag_names
      )
    end

    def proion_image_params
      params.require(:proion).permit(images: [])
    end

    #eikonas_attributes: [:id, :_destroy, :path_ref, :thumbnail, :image]

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/proions_helper.rb
# frozen_string_literal: true

module ProionsHelper
end

app/views/proions/_proion.html.erb
<%
    eikona = proion.eikonas.present? && proion.eikonas.find_by(thumbnail: "true").present? ? proion.eikonas.find_by(thumbnail: "true") : ""
%>
<div class="columns is-flex " >
  <div class="column is-12">
    <div id="card-item-product" class = "is-flex is-flex-direction-column " >
      <a href="#" class="is-flex"  data-controller="product" data-product-load-path="<%= proion_path(locale: I18n.locale, id: proion) %>" data-action="click->product#getProduct" data-product-id="<%= proion.id %>">
        <div class="product-image is-flex is-align-center is-justify-content-center"style="position:relative">
          <span class="is-flex is-align-items-center is-justify-content-center">
            <% if eikona.present? && eikona.respond_to?(:image) && eikona.image.attached? %>
              <%= image_tag(proion.eikonas.find_by(thumbnail: "true").image, :size => "80x80",style:"margin:0 auto;") %>
            <% else %>
              <%= image_tag("domestos.png", :size => "80x80",style:"margin:0 auto;") %>
            <% end %>
          </span>
          <a href="#" data-controller="add-to-cart" data-add-to-cart-load-path="<%= line_items_path(:product_id => proion.id) %>" data-action="click->add-to-cart#fillCart" style="z-index: 1;">
            <%= image_tag("plus-svgrepo-com.svg", :size => "80x80", :class => "add-icon") %>
          </a>
        </div>
      </a>
      <div class="has-text-left">
        <p style="margin-top: 5px;"><span class="subtitle is-7" style="color: #f14668; font-weight: 700;"><%= proion.price %> <span class="currency"><%= t('carts.cart_nav.den') %></span></span> <% if proion.previous_price.present? %><span class="subtitle is-7" style="opacity: 0.7; font-size: 0.6rem;"><del><%= proion.price %> <span class="currency"><%= t('carts.cart_nav.den') %></span></del></span><% end %></p>
        <span style="position: relative; top: -5px; " class="subtitle is-9 is-bold is-black">
          <%= truncate(proion.title, length: 16) %>
        </span>
        <p><span class="subtitle is-7"><%= proion.price_per_size %> <span class="currency"><%= t('carts.cart_nav.den') %></span> / <%=  proion.size %> </span></p>
      </div>
    </div>
  </div>
</div>

app/views/proions/_proion_details.html.erb
<%
    eikona = proion.eikonas.present? && proion.eikonas.find_by(thumbnail: "true").present? ? proion.eikonas.find_by(thumbnail: "true") : ""
%>
<div id="product-details-section" class="column is-12 is-flex is-flex-direction-mobile-desktop">
  <div class="column is-6">
    <div class="carousel carousel-animated carousel-animate-fade" data-controller="carousel">
      <div class="carousel-container" style="background: #f5f5f5; border-radius: 8px;">
        <% proion.eikonas.each_with_index do |eikona, index| %>
          <div class="carousel-item has-background is-flex" data-index="<%= index %>">
            <img src="<%= url_for(eikona.image) %>" alt="Image <%= index + 1 %>">
          </div>
        <% end %>
      </div>
      <div class="carousel-navigation is-overlay">
        <% if proion.present? && proion.eikonas.present? && proion.eikonas.length > 1 %>
          <div class="carousel-nav-left">
            <i class="fas fa-chevron-left" aria-hidden="true" data-action="click->carousel#changeSlide" data-carousel-offset="-1"></i>
          </div>
          <div class="carousel-nav-right">
            <i class="fas fa-chevron-right" aria-hidden="true" data-action="click->carousel#changeSlide" data-carousel-offset="1"></i>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="column is-6 is-flex">
    <div class="is-flex is-flex-direction-column">
      <p class="title"><%= proion.title %></p>
      <p class="subtitle-adjusted" style="font-weight: 500;"><span class="subtitle-adjusted is-7"><%= proion.price %> <span class="currency"><%= t('carts.cart_nav.den') %></span> / <%=  proion.size %> </span></p>
      <p class="subtitle mt-6"><%= t('proions.proion.proion_information') %></p>
      <p class="subtitle is-6" style="white-space: pre-line;"><%= proion.long_description %></p>
      <a class="button is-danger" data-controller="add-to-cart" data-add-to-cart-load-path="<%= line_items_path(:product_id => proion.id) %>" data-action="click->add-to-cart#fillCart"><%= t('proions.proion.add_item') %></a>
    </div>
  </div>
</div>

app/views/proions/index.html.erb
<%= render @proions %>

app/views/proions/show.html.erb
<%= render 'shared/navbar/main' %>
<div id="product-details">
    <%= render @proion, show: true %>
</div>
<!-- Loader 4 -->
<div id="loader-4" class="loader-4 center"><span></span></div>